### ISSUE TITLE
代码块左上角图标缩放异常

### ISSUE THREAD

**Issue by tdwxz** [chenshinshi/zhang-dark#1]
打开文档的时候左上角的三个点显示正常,  之后任意操作(复制代码, 甚至按了任何一个按键)后就会缩放异常, 如下图: 
![image](https://github.com/chenshinshi/zhang-dark/assets/79458678/6a22cbb3-aec3-4dce-8a72-356554223336)

**Comment by chenshinshi** [comment]
我这边没法复现，可以详细录制下步骤吗？

**Comment by tdwxz** [comment]
好的, 我发现当代码处于列表内部的时候才会出现这个问题, 我录制了一个视频

https://github.com/chenshinshi/zhang-dark/assets/79458678/d17ec640-fca0-4e29-a3a2-c12624099008

**Comment by chenshinshi** [comment]
![image](https://github.com/chenshinshi/zhang-dark/assets/125173405/4b3a81cb-233d-46d3-bb9b-5f611559af26)
我这边还是没法复现，你看下是否有其他插件和代码片段冲突？

**Comment by tdwxz** [comment]
是和代码片段冲突了，我用了瑞姆工艺的子弹线CSS，禁用后OK了，感谢作者大大帮忙
